; Joystick
JOYSTICK_INPUT = $02
JOYSTICK_INPUT1 = $02
JOYSTICK_MASK_RIGHT = %00001000
JOYSTICK_MASK_LEFT  = %00000100 
JOYSTICK_MASK_UP    = %00000001 
JOYSTICK_MASK_DOWN  = %00000010
JOYSTICK_MASK_BTN   = %00010000  

; UI
BOX_SELECTOR_TL byte $70
BOX_SELECTOR_TR byte $6E
BOX_SELECTOR_BL byte $6D
BOX_SELECTOR_BR byte $7D

; Player
PLAYER_SPRITE_INDEX byte $80
PLAYER_X byte $15
PLAYER_Y byte $32
PLAYER_ACTION = #1
PLAYER_MOVED_UP = #2
PLAYER_MOVED_RIGHT = #4
PLAYER_MOVED_DOWN = #8
PLAYER_MOVED_LEFT = #16
PLAYER_IDLE byte $80
PLAYER_RIGHT byte $81
PLAYER_LEFT byte $83
PLAYER_UP byte $85
PLAYER_DOWN byte $87

; Player Actions
PLAYER_ACTION_SHOOT = #%00000001
PLAYER_ACTION_TALK = #%00000010
PLAYER_ACTION_USE = #%00000100

; Player Bullet
PLAYER_BULLET_SPRITE_INDEX byte $93
PLAYER_BULLET_X byte $15
PLAYER_BULLET_Y byte $32
PLAYER_BULLET_HORI byte $93
PLAYER_BULLET_VERT byte $94
PLAYER_BULLET_NWSE byte $95
PLAYER_BULLET_SWNE byte $96
PLAYER_BULLET_EXPLOSION1 byte $97
PLAYER_BULLET_EXPLOSION2 byte $98
PLAYER_BULLET_EXPLOSION3 byte $99
PLAYER_BULLET_EXPLOSION4 byte $9a
PLAYER_BULLET_EXPLOSION5 byte $9b

;Door
DOOR_SPRITE_INDEX byte $9c
DOOR_X byte $f8
DOOR_Y byte $b3
DOOR_FRAME1 byte $9c
DOOR_FRAME2 byte $9d
DOOR_FRAME3 byte $9e
DOOR_FRAME4 byte $9f
DOOR_FRAME5 byte $a0

;horizontal door
HORI_DOOR_SPRITE_INDEX byte $a1
HORI_DOOR_X byte $0f
HORI_DOOR_Y byte $a2
HORI_DOOR_FRAME1 byte $a1
HORI_DOOR_FRAME2 byte $a2
HORI_DOOR_FRAME3 byte $a3
HORI_DOOR_FRAME4 byte $a4
HORI_DOOR_FRAME5 byte $a5

; Button
BUTTON_SPRITE_INDEX byte $a6
BUTTON_X byte $f1
BUTTON_Y byte $da
BUTTON_FRAME1 byte $a6
BUTTON_FRAME2 byte $a7
BUTTON_FRAME3 byte $a8

BUTTON2_SPRITE_INDEX byte $a6
BUTTON2_X byte $0
BUTTON2_Y byte $80
BUTTON2_FRAME1 byte $a6
BUTTON2_FRAME2 byte $a7
BUTTON2_FRAME3 byte $a8

; NPCs
NPC1_SPRITE_INDEX byte $80
NPC2_SPRITE_INDEX byte $80
NPC1_X byte $52
NPC1_Y byte $d7
NPC2_X byte $0f
NPC2_Y byte $80

; Animation
PLAYER_RIGHT_ANIM1 = #$81
PLAYER_RIGHT_ANIM2 = #$82
PLAYER_LEFT_ANIM1  = #$83 
PLAYER_LEFT_ANIM2  = #$84
PLAYER_UP_ANIM1    = #$85
PLAYER_UP_ANIM2    = #$86
PLAYER_DOWN_ANIM1  = #$87
PLAYER_DOWN_ANIM2  = #$88
PLAYER_DYING_ANIM1 = #$89
PLAYER_DYING_ANIM2 = #$8A
PLAYER_SHOOT_N = #$8B
PLAYER_SHOOT_NE = #$8C
PLAYER_SHOOT_E = #$8D
PLAYER_SHOOT_SE = #$8E
PLAYER_SHOOT_S = #$8F
PLAYER_SHOOT_SW = #$90
PLAYER_SHOOT_W = #$91
PLAYER_SHOOT_NW = #$92

; Colours
COLOUR_BLACK = #0
COLOUR_WHITE = #1
COLOUR_RED = #2
COLOUR_CYAN = #3
COLOUR_LIGHT_BLUE = #14

; Dialogue window configuration
DIALOGUE_WINDOW_TOP = $06D0
DIALOGUE_WINDOW_WIDTH = #40
DIALOGUE_WINDOW_HEIGHT = #5
DIALOGUE_WINDOW_BOTTOM = DIALOGUE_WINDOW_TOP + 160
DIALOGUE_TEXT_WIDTH = #38
DIALOGUE_TEXT_LINES = #3
DIALOGUE_LAST_ROW = DIALOGUE_TEXT_LINES - 1
DIALOGUE_PRINT_DELAY = #2
DIALOGUE_TONE_INTERVAL = #3
DIALOGUE_BLINK_INTERVAL = #12
DIALOGUE_NEWLINE = #$0D
DIALOGUE_BORDER_TL = BOX_SELECTOR_TL
DIALOGUE_BORDER_TR = BOX_SELECTOR_TR
DIALOGUE_BORDER_BL = BOX_SELECTOR_BL
DIALOGUE_BORDER_BR = BOX_SELECTOR_BR
DIALOGUE_BORDER_HORIZONTAL = #$71
DIALOGUE_BORDER_VERTICAL = #$72
DIALOGUE_TEXT_COLOUR = COLOUR_WHITE
DIALOGUE_INDICATOR_CHAR = #$1E
DIALOGUE_WINDOW_CHAR_COUNT = #200

DIALOGUE_TEXT_START = DIALOGUE_WINDOW_TOP + 41
DIALOGUE_TEXT_LINE1 = DIALOGUE_TEXT_START
DIALOGUE_TEXT_LINE2 = DIALOGUE_TEXT_START + 40
DIALOGUE_TEXT_LINE3 = DIALOGUE_TEXT_START + 80

DIALOGUE_COLOUR_BASE = COLOUR_RAM + (DIALOGUE_WINDOW_TOP - SCREEN_BLOCK1)
DIALOGUE_COLOUR_LINE1 = DIALOGUE_COLOUR_BASE + 41
DIALOGUE_COLOUR_LINE2 = DIALOGUE_COLOUR_LINE1 + 40
DIALOGUE_COLOUR_LINE3 = DIALOGUE_COLOUR_LINE2 + 40

DIALOGUE_INDICATOR_POSITION = DIALOGUE_TEXT_LINE3 + (DIALOGUE_TEXT_WIDTH - 1)
DIALOGUE_INDICATOR_COLOUR_POS = DIALOGUE_COLOUR_LINE3 + (DIALOGUE_TEXT_WIDTH - 1)

; Dialogue state
DIALOGUE_STATE byte 0
DIALOGUE_COLUMN byte 0
DIALOGUE_CURRENT_ROW byte 0
DIALOGUE_DELAY_COUNTER byte 0
DIALOGUE_BUTTON_LATCH byte 0
DIALOGUE_TONE_COUNTER byte 0
DIALOGUE_INDICATOR_COUNTER byte 0
DIALOGUE_INDICATOR_VISIBLE byte 0

DialogueScreenLinePointers
        word DIALOGUE_TEXT_LINE1
        word DIALOGUE_TEXT_LINE2
        word DIALOGUE_TEXT_LINE3

DialogueColourLinePointers
        word DIALOGUE_COLOUR_LINE1
        word DIALOGUE_COLOUR_LINE2
        word DIALOGUE_COLOUR_LINE3

DIALOGUE_SCREEN_BACKUP
        ds DIALOGUE_WINDOW_CHAR_COUNT

DIALOGUE_COLOUR_BACKUP
        ds DIALOGUE_WINDOW_CHAR_COUNT

NPC1_DIALOGUE
        text "KEEP YOUR VOICE LOW INSIDE HALLS."
        byte DIALOGUE_NEWLINE
        text "LISTEN FOR THE RHYTHM BETWEEN LIGHTS."
        byte DIALOGUE_NEWLINE
        text "WHEN IT SWELLS, TAKE YOUR CHANCE."
        byte 0

NPC2_DIALOGUE
        text "I WATCH THE DOORS FOR SIGNS OF RETURN."
        byte DIALOGUE_NEWLINE
        text "FIND THE LEVERS TO CLEAR THE PATH."
        byte DIALOGUE_NEWLINE
        text "BRING HOPE BACK BEFORE MUSIC FADES."
        byte 0
